### ISSUE TITLE
Heroku Geos not Found

### ISSUE THREAD

**Issue by dorthwein** [dark-panda/ffi-geos#28]
So we have RGeo working without the gem using a build back however if we include this gem, it seems Geos can't be found.  We've tried setting the environment variables manually etc... but still no luck ;( 

Any guidance would be hugely appreciated!

**Comment by dark-panda** [comment]
Are you able to set environment variables that your application can see when starting up? You can provide the GEOS_LIBRARY_PATH environment variable to point to the libgeos_c library you need to access to use the extension. It might be in a non-standard location or somewhere unexpected, so you might have to check how heroku installs its libraries, but that should fix things up.

**Comment by dark-panda** [comment]
Any luck here? Does setting `GEOS_LIBRARY_PATH` help?

**Comment by Mihail-K** [comment]
The path of the build and its dependencies aren't known ahead of time.
Here's a stack trace that demonstrates the underlying issue:
```
 !     Caused by:
 !     NoMethodError: undefined method `GEOSversion' for Geos::FFIGeos:Module
 !     /tmp/build_ca1671791f67cfad78e1e1b8ba20fc0f/vendor/bundle/ruby/2.6.0/gems/ffi-geos-2.0.0/lib/ffi-geos.rb:1084:in `<module:FFIGeos>'
 !     /tmp/build_ca1671791f67cfad78e1e1b8ba20fc0f/vendor/bundle/ruby/2.6.0/gems/ffi-geos-2.0.0/lib/ffi-geos.rb:51:in `<module:Geos>'
 !     /tmp/build_ca1671791f67cfad78e1e1b8ba20fc0f/vendor/bundle/ruby/2.6.0/gems/ffi-geos-2.0.0/lib/ffi-geos.rb:7:in `<main>'
```

Some `GEOSversion` version method is expected but not defined.

**Comment by dark-panda** [comment]
Closing due to inactivity.
